-- SkyVault MVP schema for Supabase
-- Run in Supabase SQL Editor

begin;

-- 0) Helpers
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 1) Users (extended profile)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  role text not null default 'user' check (role in ('user', 'moderator', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- 2) Skylanders catalog
create table if not exists public.skylanders (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  element text,
  series text,
  variant text,
  image_url text,
  figure_image_url text,
  card_image_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_skylanders_name on public.skylanders (name);
create index if not exists idx_skylanders_series on public.skylanders (series);

-- 3) Price observations
create table if not exists public.skylander_prices (
  id bigint generated by default as identity primary key,
  skylander_id bigint not null references public.skylanders(id) on delete cascade,
  source text not null,
  currency char(3) not null default 'EUR',
  price_cents integer not null check (price_cents >= 0),
  observed_at timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_prices_skylander_observed on public.skylander_prices (skylander_id, observed_at desc);
create index if not exists idx_prices_currency on public.skylander_prices (currency);

-- 4) User collection
create table if not exists public.user_collection (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  skylander_id bigint not null references public.skylanders(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  item_condition text not null default 'loose' check (item_condition in ('loose', 'boxed', 'new')),
  acquired_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, skylander_id, item_condition)
);

create index if not exists idx_collection_user on public.user_collection (user_id);
create index if not exists idx_collection_skylander on public.user_collection (skylander_id);

drop trigger if exists trg_collection_updated_at on public.user_collection;
create trigger trg_collection_updated_at
before update on public.user_collection
for each row execute function public.set_updated_at();

-- 5) Friendships
create table if not exists public.friendships (
  user_id uuid not null references public.users(id) on delete cascade,
  friend_user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, friend_user_id),
  check (user_id <> friend_user_id)
);

create index if not exists idx_friendships_friend on public.friendships (friend_user_id);

drop trigger if exists trg_friendships_updated_at on public.friendships;
create trigger trg_friendships_updated_at
before update on public.friendships
for each row execute function public.set_updated_at();

-- 6) Daily snapshots
create table if not exists public.collection_value_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  snapshot_date date not null default current_date,
  total_value_cents bigint not null default 0 check (total_value_cents >= 0),
  item_count integer not null default 0 check (item_count >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, snapshot_date)
);

create index if not exists idx_snapshots_user_date on public.collection_value_snapshots (user_id, snapshot_date desc);

-- 7) Enable RLS
alter table public.users enable row level security;
alter table public.skylanders enable row level security;
alter table public.skylander_prices enable row level security;
alter table public.user_collection enable row level security;
alter table public.friendships enable row level security;
alter table public.collection_value_snapshots enable row level security;

-- 8) Policies: users
drop policy if exists "users_select_self" on public.users;
create policy "users_select_self"
on public.users for select
using (auth.uid() = id);

drop policy if exists "users_insert_self" on public.users;
create policy "users_insert_self"
on public.users for insert
with check (auth.uid() = id);

drop policy if exists "users_update_self" on public.users;
create policy "users_update_self"
on public.users for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- 9) Policies: skylanders (public read, moderator write)
drop policy if exists "skylanders_read_all" on public.skylanders;
create policy "skylanders_read_all"
on public.skylanders for select
to anon, authenticated
using (true);

drop policy if exists "skylanders_write_moderator" on public.skylanders;
create policy "skylanders_write_moderator"
on public.skylanders for all
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('moderator', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('moderator', 'admin')
  )
);

-- 10) Policies: skylander_prices
drop policy if exists "prices_read_all" on public.skylander_prices;
create policy "prices_read_all"
on public.skylander_prices for select
to anon, authenticated
using (true);

drop policy if exists "prices_write_moderator" on public.skylander_prices;
create policy "prices_write_moderator"
on public.skylander_prices for all
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('moderator', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('moderator', 'admin')
  )
);

-- 11) Policies: user_collection
drop policy if exists "collection_select_own" on public.user_collection;
create policy "collection_select_own"
on public.user_collection for select
using (auth.uid() = user_id);

drop policy if exists "collection_insert_own" on public.user_collection;
create policy "collection_insert_own"
on public.user_collection for insert
with check (auth.uid() = user_id);

drop policy if exists "collection_update_own" on public.user_collection;
create policy "collection_update_own"
on public.user_collection for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "collection_delete_own" on public.user_collection;
create policy "collection_delete_own"
on public.user_collection for delete
using (auth.uid() = user_id);

-- 12) Policies: friendships
drop policy if exists "friendships_select_own" on public.friendships;
create policy "friendships_select_own"
on public.friendships for select
using (auth.uid() = user_id);

drop policy if exists "friendships_insert_own" on public.friendships;
create policy "friendships_insert_own"
on public.friendships for insert
with check (auth.uid() = user_id);

drop policy if exists "friendships_update_own" on public.friendships;
create policy "friendships_update_own"
on public.friendships for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "friendships_delete_own" on public.friendships;
create policy "friendships_delete_own"
on public.friendships for delete
using (auth.uid() = user_id);

-- 13) Policies: snapshots
drop policy if exists "snapshots_select_own" on public.collection_value_snapshots;
create policy "snapshots_select_own"
on public.collection_value_snapshots for select
using (auth.uid() = user_id);

drop policy if exists "snapshots_insert_own" on public.collection_value_snapshots;
create policy "snapshots_insert_own"
on public.collection_value_snapshots for insert
with check (auth.uid() = user_id);

drop policy if exists "snapshots_update_own" on public.collection_value_snapshots;
create policy "snapshots_update_own"
on public.collection_value_snapshots for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "snapshots_delete_own" on public.collection_value_snapshots;
create policy "snapshots_delete_own"
on public.collection_value_snapshots for delete
using (auth.uid() = user_id);

commit;
